-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 02:49:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Tiendecita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tiendecita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tiendecita` DEFAULT CHARACTER SET ISO-8859-1  ;
USE `Tiendecita` ;

-- -----------------------------------------------------
-- Table `Tiendecita`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tiendecita`.`Articulos` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `descripcionArticulo` VARCHAR(45) NOT NULL,
  `precioArticulo` DECIMAL(5,2) NOT NULL,
  `cantidadArticulo` INT(3) NOT NULL,
  PRIMARY KEY (`idArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tiendecita`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tiendecita`.`Tickets` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `idArticuloFK` INT NOT NULL,
  `descripcionArticuloFK` VARCHAR(45) NOT NULL,
  `fechaTicket` VARCHAR(45) NOT NULL,
  `totalTicket` DECIMAL(5,2) NOT NULL,
  `cantidadArtiTick` INT NOT NULL,
  PRIMARY KEY (`idTicket`, `idArticuloFK`),
  INDEX `idArticuloFK_idx` (`idArticuloFK` ASC) VISIBLE,
  CONSTRAINT `idArticuloFK`
    FOREIGN KEY (`idArticuloFK`)
    REFERENCES `Tiendecita`.`Articulos` (`idArticulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `descripcionArticuloFK`
    FOREIGN KEY (`idArticuloFK`)
    REFERENCES `Tiendecita`.`Articulos` (`idArticulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
